### ISSUE TITLE
truffle console里面什么时候创建MetaCoin这个对象的？

### ISSUE THREAD

**Issue by hsuxinxin** [Guigulive/Wiki#5]
在教程视频中，如图所示，没看到MetaCoin这个对象是怎么创建的? Truffle console是怎么知道我有一个合约叫MetaCoin的？如果这个测试网络里面有两个人分别部署了两个合约都叫MetaCoin呢？这个命令调用的是哪一个合约？
<img width="832" alt="2018-03-22 8 16 08" src="https://user-images.githubusercontent.com/1861803/37770531-ae1b558c-2e0f-11e8-99a7-303252d53d29.png">

**Comment by minzhi3** [comment]
执行完compile后本地会有一个json文件，truffle会自动读取
再执行migrate部署以后json文件上会有合约地址。

**Comment by hsuxinxin** [comment]
@minzhi3 谢谢
